server:
  port: 8081
  servlet:
    session:
     tracking-modes: cookie
runtime: java11
spring:
  hikari:
    datasource:
      url: jdbc:postgresql://116.35.177.202:5432/postgres
      username: postgres
      password: 1234
      driver-class-name: org.postgresql.Driver
      idle-timeout: 10000
      max-lifetime: 420000
      connection-timeout : 10000
      validation-timeout : 10000
    url: jdbc:postgresql://116.35.177.202:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://116.35.177.202:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

mybatis:
  type-aliases-package: com.example.dogeapi
  mapper-locations: classpath:mappers/**/*.xml
